_BASE_: "../base-prompt.yaml"
RUN_N_TIMES: 100
DATA:
  NAME: "pvt"
  DATAPATH: "Datasets/PV_ID_Tomato"   #TODO: need to specify here
  NUMBER_CLASSES: 10
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001